services:
  emsdk:
    container_name: emsdk-container
    build:
      context: tools/emsdk
      dockerfile: Dockerfile
    working_dir: /work
    volumes:
      - $PWD:/work
  binaryen:
    container_name: binaryen-container
    build:
      context: tools/binaryen
      dockerfile: Dockerfile
    working_dir: /work
    volumes:
      - $PWD:/work
  wabt:
    container_name: wabt-container
    build:
      context: tools/wabt
      dockerfile: Dockerfile
    working_dir: /work
    volumes:
      - $PWD:/work
